### ISSUE TITLE
Error with CodeChickenLib

### ISSUE THREAD

**Issue by xJon** [delvr/Streams#116]
Hi,
We got this message in the client log:
```
[14:31:49] [Chunk Batcher 2/ERROR]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-574, y:64, z:-312
  Block Class:   class streams.block.BlockRiver
  Registry Name: streams:river/tile.water/0/2
  Metadata:      0
  State:         streams:river/tile.water/0/2[level=0]
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block in world
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderBlock(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:200) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.NoClassDefFoundError: farseek/util/ImplicitConversions$
	at streams.block.BlockRiver.getFlow(BlockRiver.scala:78) ~[BlockRiver.class:?]
	at streams.block.package$.getSlopeAngle(package.scala:20) ~[package$.class:?]
	at streams.block.package.getSlopeAngle(package.scala) ~[package.class:?]
	at net.minecraft.client.renderer.BlockFluidRenderer.renderFluid(BlockFluidRenderer.java:80) ~[bvn.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:84) ~[bvm.class:?]
	... 5 more
```

Any idea what's causing this? Thanks!

**Comment by xJon** [comment]
This might have been caused due to a change of world gen mods?
![image](https://user-images.githubusercontent.com/8945347/121269574-c049ab80-c8c8-11eb-9c0c-56e8e561071f.png)
