### ISSUE TITLE
Minecraft 1.7.10 crashes while FML is "initializing" Streams. (With TFC installed)

### ISSUE THREAD

**Issue by recolic** [delvr/Streams#54]
## Installation info

Game version: 1.7.10

Forge: 10.13.4.1614

Mod list: `core-Streams-1.7.10-0.3.3.jar  core-tfc-0.79.29.922.jar  lib-Farseek-1.7.10-2.0.1.jar`

OS: `Linux RECOLICPC 4.15.3-1-ARCH #1 SMP PREEMPT Mon Feb 12 23:01:17 UTC 2018 x86_64 GNU/Linux`

JRE: Openjdk 1.8.0_144

## What happeded

I failed to launch minecraft with both TFC and Streams installed. Remove either one of them, everything is OK.

Refer to [here](https://recolic.net/tmp/stream-tfc-crash.log) for full launcher log.

Crash report:
```
---- Minecraft Crash Report ----
// Oops.

Time: 18-2-19 下午6:41
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:121)
Caused by: java.lang.ExceptionInInitializerError
	at streams.StreamsMod$.handle(StreamsMod.scala:24)
	at streams.StreamsMod.handle(StreamsMod.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 15 more
Caused by: java.lang.NullPointerException
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
	at java.lang.reflect.Field.get(Field.java:393)
	at farseek.util.Reflection$FieldValue$.value$extension(Reflection.scala:46)
	at farseek.util.Reflection$FieldValue$.copyValue$extension(Reflection.scala:50)
	at farseek.util.Reflection$$anonfun$cloneObject$2.apply(Reflection.scala:30)
	at farseek.util.Reflection$$anonfun$cloneObject$2.apply(Reflection.scala:30)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at farseek.util.Reflection$.cloneObject(Reflection.scala:30)
	at streams.block.BlockRiver.<init>(BlockRiver.scala:34)
	at streams.block.FixedFlowBlock$$anonfun$2$$anonfun$apply$2$$anonfun$apply$3.apply(FixedFlowBlock.scala:20)
	at streams.block.FixedFlowBlock$$anonfun$2$$anonfun$apply$2$$anonfun$apply$3.apply(FixedFlowBlock.scala:19)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at streams.block.FixedFlowBlock$$anonfun$2$$anonfun$apply$2.apply(FixedFlowBlock.scala:19)
	at streams.block.FixedFlowBlock$$anonfun$2$$anonfun$apply$2.apply(FixedFlowBlock.scala:19)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at streams.block.FixedFlowBlock$$anonfun$2.apply(FixedFlowBlock.scala:19)
	at streams.block.FixedFlowBlock$$anonfun$2.apply(FixedFlowBlock.scala:18)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.immutable.List.flatMap(List.scala:346)
	at streams.block.FixedFlowBlock$.<init>(FixedFlowBlock.scala:18)
	at streams.block.FixedFlowBlock$.<clinit>(FixedFlowBlock.scala)
	... 44 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.15.3-1-ARCH
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 68212856 bytes (65 MB) / 247406592 bytes (235 MB) up to 5335154688 bytes (5088 MB)
	JVM Flags: 10 total; -XX:SurvivorRatio=2 -XX:+DisableExplicitGC -XX:+AggressiveOpts -Xincgc -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx5120m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	tfc_coremod{0.79.29} [TFC[coremod]] (minecraft.jar) 
	UCE	streams{0.3.3} [Streams] (core-Streams-1.7.10-0.3.3.jar) 
	UCH	terrafirmacraft{0.79.29} [TerraFirmaCraft] (core-tfc-0.79.29.922.jar) 
	UCH	farseek{2.0.1} [Farseek] (lib-Farseek-1.7.10-2.0.1.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.25' Renderer: 'GeForce GTX 950M/PCIe/SSE2'
```

Minimal reproduce: [DOWNLOAD](https://recolic.net/tmp/MinecraftClientByRecolic-TFC18.tar.gz)

**Comment by delvr** [comment]
Hi recolic, thanks for reporting. I haven't been able to reproduce your crash however. Your Forge environment seems relatively clean with no extra mods interfering, so I'm not sure what might be causing this. Looking at this line in your logs:
`Searching /home/recolic/program/MinecraftClientByRecolic-127/.minecraft/mods-buggy-tfc18 for mods` does make me wonder - do you have any non-standard loader or mod installed? Or perhaps multiple copies of the Farseek/Streams mods? You could perhaps retry with freshly-downloaded copies of TFC, Farseek and Streams. Anyway, thanks for letting me know.

**Comment by recolic** [comment]
@delvr I had:
`ln -s mods-tfc18-buggy mods` for debug, and
`ln -s mods-tfc18 mods` on usual... 

It's just a symbolic link, for switching between many mods/config.

I'll try to reinstall everything in a new virtual machine in a few days...

**Comment by recolic** [comment]
I'm sorry that I failed to reproduce this issue in a freshly-installed ArchLinux VirtualMachine... However I still doesn't know what caused my crash... This is a "fake" issue and I'll close it.

**Comment by delvr** [comment]
Thanks for investigating and letting me know! If you find that this happens again, feel free to re-open this issue. Cheers!

**Comment by brandyyn** [comment]
Hi, I'm getting the same crash, Anything I can do to fix it ?

**Comment by brandyyn** [comment]
This is my log as I dont get a crash report: https://pastebin.com/TSddzNA5

**Comment by recolic** [comment]
@sonicbrandyn I'm not sure what happened. If it's possible, you can create a new VM, install new Minecraft+Forge+mods, and everything is OK. That's how do I solve my problem.

**Comment by delvr** [comment]
@sonicbrandyn I looked at your crash report and it doesn't seem to have anything in common with this issue except for happening during initialization, unless I missed something. Could you create a new issue for it?

Anway there seems to be a lot of mods involved in the crash so it might be difficult to investigate. But since the crash happens while reading a zip file, could you try looking in your mods/ folder and subfolders for any files with a `.jar` extension that aren't actually zipped Java jars? Thanks.

**Comment by brandyyn** [comment]
oh no it always says that, even without a crash; the crash only happens when I add farseek and streams.

**Comment by delvr** [comment]
So is the log incomplete? The last stack trace I see is one of the `ZipException`s.

**Comment by brandyyn** [comment]
It looks complete to me? ([18:01:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 6 more) is the final line i see

**Comment by brandyyn** [comment]
line 404
