### ISSUE TITLE
[Server thread/INFO] [STDERR] when using the OreLib mod

### ISSUE THREAD

**Issue by Dwayne103** [delvr/Streams#94]
Good day

So I get these errors when using this mod with DynamicSurroundings and DynamicSurroundings which both require the OreLib mod to work. Is this fixable? This is an amazing mod and I'd like to add this to my modpack I'm working on.

21:01:25.891
[21:01:25] [Server thread/INFO] [STDERR]: [org.orecruncher.lib.VersionChecker:playerLogin:75]: 	at com.google.gson.internal.Streams.parse(Streams.java:60)
21:01:25.914
[21:01:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at com.google.gson.internal.Streams.parse(Streams.java:46)

![Annotation 2019-11-12 210230](https://user-images.githubusercontent.com/35834591/68701589-cada7c80-058f-11ea-99c4-2ff624090b12.png)

Kind regards
Dwayne103

**Comment by delvr** [comment]
The `com.google.gson.internal.Streams` in the stack trace is not related to the Streams mod, it's a Google library used by a variety of mods. Do you only see those when using the Streams mod?

**Comment by Dwayne103** [comment]
Yes I only get those errors when using streams together with orelib, when I remove the orelib mod streams work fine and as intended
